[package]

name = "piston2d-sprite"
version = "0.0.3"
authors = [
    "Coeuvre Wong <coeuvre@gmail.com>",
    "zummenix",
    "bvssvni <bvssvni@gmail.com>"
]
keywords = ["sprite", "animation", "2d", "piston"]
description = "A library for sprite hierarchy and scene management"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/sprite.git"
homepage = "https://github.com/pistondevelopers/sprite"

[lib]

name = "sprite"
path = "./src/lib.rs"

[dependencies.pistoncore-event]
git = "https://github.com/pistondevelopers/event"
#version = "0.1.0"

[dependencies.interpolation]
git = "https://github.com/pistondevelopers/interpolation"
#version = "0.0.4"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"
#version = "0.0.26"

[dependencies.piston-ai_behavior]
git = "https://github.com/pistondevelopers/ai_behavior"
#version = "0.0.3"

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid"
#version = "0.1.15"

